### ISSUE TITLE
tpcds-single table cardinality estimation

### ISSUE THREAD

**Issue by wuziniu** [DataManagementLab/deepdb-public#6]
I wonder if it is possible to do single table (single SPN) cardinality estimation without modifying the code in SPNensemble class. I tried with a single table toy dataset and it run into a lot of errors. I assume you must have tested the code on single table first before making it work on multiple tables. Could you let me know how to estimate on single table?
Thanks a lot.

**Comment by bhilprecht** [comment]
This is absolutely possible. For instance, the section "TPC-DS (Single Table) pipeline" in the README describes how to use DeepDB for a setup with just a single tpcds table. If want a smaller toy table, you can also just generate the 1gb version of the tpcds table. I hope this helps.
Best, 
Benjamin

**Comment by wuziniu** [comment]
@bhilprecht Thanks for your reply. For that part I totally understand how to train a single table rspn and the readme explained how to run aqp. However, to estimate cardinality of that single error, I run into a lot of errors since first_spn, next_mergeable_relationships, next_mergeable_tables returned by  self._greedily_select_first_cardinality_spn is None. So I want to know where can is found the code for estimate cardinality for a single table?

**Comment by bhilprecht** [comment]
@wuziniu You do not need to change the code. Internally the AQP methods use the cardinality estimation methods for count queries. They pass a prototype_query to the cardinality procedures to obtain the count. For instance, the prototype_query in evaluate_query() for a count query in TPC-DS is essentially a cardinality estimation for a single table. This should give you a good example how to call the cardinality methods for a single table. I hope this helps.

**Comment by wuziniu** [comment]
Thanks @bhilprecht. That makes perfect sense now.
